name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: action-cpp-lint
      uses: CyberZHG/github-action-cpp-lint@0.0.2
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1


