name: cpp-lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: action-cpp-lint
      uses: cclauss/GitHub-Action-for-cpplint@0.0.6
